POST http://localhost:8888/register/save/?trace=true&message=true
Content-Type: application/json

{
  "firstName":"Mateusz",
  "password":"haslo123!",
  "lastName":"Testowy",
  "email":"strzelnicanozyno1@gmail.com"

}



